# recipes/recipe.yml
name: my-custom-kde-linux
description: An immutable KDE Plasma distro with Snap and Flatpak support.

# Base image provides the immutable KDE Plasma environment
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # 1. Install Snapd and system tools via rpm-ostree
  - type: rpm-ostree
    install:
      - snapd
      - rsync # Useful for maintenance

  # 2. Enable Snap services to start automatically
  - type: systemd
    units:
      - snapd.socket

  # 3. Create the /snap symlink at boot using systemd-tmpfiles
  # This is required for "classic" snaps like LXD or VS Code.
  - type: script
    scripts:
      - |
        mkdir -p /usr/lib/tmpfiles.d
        echo "L+ /snap - - - - /var/lib/snapd/snap" > /usr/lib/tmpfiles.d/snap.conf

  # 4. Pre-install essential Flatpaks
  - type: flatpaks
    install:
      - org.kde.dolphin
      - com.discordapp.Discord
      - org.mozilla.firefox

  # 5. Enable Flathub by default
  - type: default-flatpaks
    notify: true
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub
    repo-title: "Flathub (Official)"
